### PR TITLE
added function to clean country name spelling

### PR DESCRIPTION
**Pull request by kevanpng**
Use TextBlob to check spelling for country name. Done together with Louis.

### CODE REVIEW

**Comment by kevanpng** [comment]
Hi Paul,
i originally made a branch from this repo and when trying to push, I get the following error:
```remote: Permission to DataKind-SG/wpdx.git denied to kevanpng.
fatal: unable to access 'https://github.com/DataKind-SG/wpdx.git/': The requested URL returned error: 403
```
That's why I forked the repo, made my changes and issue a PR here. 

If you could grant me access to push a branch to the repo, that would be great

**Comment by whatevergeek** [comment]
@kevanpng 
thanks for the info
would you be able to do the following approach?

1. Fork the repo (which you have done)
2. In your own repo, create a feature-branch as per TDDC documentation.
3. Send pull request from your feature-branch to wpdx master branch
i.e. send PR to DataKind-SG:master from kevanpng:test_clean_col_country_name

Let me know if this works or if you face any issue.

**Comment by whatevergeek** [comment]
additional comments on PR:
are you able to to modify code to just have the following function signature?

def clean_col_country_name(input_data):
"""
Clean values in column: "country_name"
Trello card: https://trello.com/c/HHzNs0hS/1-column-countryname
"""
cleaned_data = input_data
## do some cleanin on cleaned_data

return cleaned data

if there's any additional function you need for the cleaning, can you store them into a separate file (e.g. clean_col_country_name_helper.py)
then reference it inside clean_wpdx_sample_data.py (e.g. import clean_col_country_name_helper)

apart from clean_wpdx_sample_data.py, please also submit your updated version of test_clean_wpdx_sample_data.py
this should contain a test function that tests your clean_col_country_name function

we follow such conventions to make it work with other TDDC hooks.

feel free to let us know if you have additional inquiries

**Comment by whatevergeek** [comment]
hi @kevanpng , 
any update on this? 
let me know what's the plan or if you'd like other volunteers to continue on this.

have a great day!

**Comment by Yustynn** [comment]
@whatevergeek I've resolved this one with #19. Assuming it's accepted, you can close this one too.

**Pull request closed without merging**
